language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  global:
    # MUST UPDATE THIS FOR YOUR EXTENSION
    - VENDOR="acme"
    - NAME="demo"
  matrix:
    - DB=mysql

branches:
  only:
    - master
    - /^develop-.*$/

install:
  # checkout phpBB and move your extension in place
  - mkdir ../../tmp
  - cp -R . ../../tmp
  - cd ../../
  - git clone "git://github.com/phpbb/phpbb.git" "phpBB3"
  - mkdir phpBB3/phpBB/ext
  - mkdir phpBB3/phpBB/ext/$VENDOR
  - mv tmp phpBB3/phpBB/ext/$VENDOR/$NAME
  - cd phpBB3

  # phpBB install Task
  - sh -c "if [ '$DB' = 'mariadb' ]; then travis/setup-mariadb.sh; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then travis/setup-php-extensions.sh; fi"
  - sh -c "if [ `php -r "echo (int) version_compare(PHP_VERSION, '5.3.19', '>=');"` = "1" ]; then travis/setup-webserver.sh; fi"
  - cd phpBB
  - php ../composer.phar install --dev --no-interaction --prefer-source
  - cd ..

before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS phpbb_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database phpbb_tests;' -U postgres; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.3' -a '$DB' = 'mysql' ]; then mysql -e 'SET GLOBAL storage_engine=MyISAM;'; fi"
  - sh -c "if [ '$DB' = 'mysql' -o '$DB' = 'mariadb' ]; then mysql -e 'create database IF NOT EXISTS phpbb_tests;'; fi"

script:
  - cd build
  # @todo - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' -a '$DB' = 'mysql' ]; then ../phpBB/vendor/bin/phing sniff; fi"
  - cd ..
  - phpBB/vendor/bin/phpunit --configuration phpBB/ext/$VENDOR/$NAME/travis/phpunit-$DB-travis.xml
  # @todo - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.5' -a '$DB' = 'mysql' -a '$TRAVIS_PULL_REQUEST' != 'false' ]; then git-tools/commit-msg-hook-range.sh origin/$TRAVIS_BRANCH..FETCH_HEAD; fi"

matrix:
  include:
    - php: 5.4
      env: DB=mariadb
    - php: 5.4
      env: DB=postgres
  allow_failures:
    - php: hhvm
